// Code generated by ent, DO NOT EDIT.

package kiosksession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldIsActive, v))
}

// UnlockedUntil applies equality check predicate on the "unlocked_until" field. It's identical to UnlockedUntilEQ.
func UnlockedUntil(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldUnlockedUntil, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNEQ(FieldIsActive, v))
}

// UnlockedUntilEQ applies the EQ predicate on the "unlocked_until" field.
func UnlockedUntilEQ(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldEQ(FieldUnlockedUntil, v))
}

// UnlockedUntilNEQ applies the NEQ predicate on the "unlocked_until" field.
func UnlockedUntilNEQ(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNEQ(FieldUnlockedUntil, v))
}

// UnlockedUntilIn applies the In predicate on the "unlocked_until" field.
func UnlockedUntilIn(vs ...time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldIn(FieldUnlockedUntil, vs...))
}

// UnlockedUntilNotIn applies the NotIn predicate on the "unlocked_until" field.
func UnlockedUntilNotIn(vs ...time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNotIn(FieldUnlockedUntil, vs...))
}

// UnlockedUntilGT applies the GT predicate on the "unlocked_until" field.
func UnlockedUntilGT(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGT(FieldUnlockedUntil, v))
}

// UnlockedUntilGTE applies the GTE predicate on the "unlocked_until" field.
func UnlockedUntilGTE(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldGTE(FieldUnlockedUntil, v))
}

// UnlockedUntilLT applies the LT predicate on the "unlocked_until" field.
func UnlockedUntilLT(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLT(FieldUnlockedUntil, v))
}

// UnlockedUntilLTE applies the LTE predicate on the "unlocked_until" field.
func UnlockedUntilLTE(v time.Time) predicate.KioskSession {
	return predicate.KioskSession(sql.FieldLTE(FieldUnlockedUntil, v))
}

// UnlockedUntilIsNil applies the IsNil predicate on the "unlocked_until" field.
func UnlockedUntilIsNil() predicate.KioskSession {
	return predicate.KioskSession(sql.FieldIsNull(FieldUnlockedUntil))
}

// UnlockedUntilNotNil applies the NotNil predicate on the "unlocked_until" field.
func UnlockedUntilNotNil() predicate.KioskSession {
	return predicate.KioskSession(sql.FieldNotNull(FieldUnlockedUntil))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.KioskSession {
	return predicate.KioskSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.KioskSession {
	return predicate.KioskSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KioskSession) predicate.KioskSession {
	return predicate.KioskSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KioskSession) predicate.KioskSession {
	return predicate.KioskSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KioskSession) predicate.KioskSession {
	return predicate.KioskSession(sql.NotPredicates(p))
}
