// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/loan"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// BorrowerUpdate is the builder for updating Borrower entities.
type BorrowerUpdate struct {
	config
	hooks    []Hook
	mutation *BorrowerMutation
}

// Where appends a list predicates to the BorrowerUpdate builder.
func (_u *BorrowerUpdate) Where(ps ...predicate.Borrower) *BorrowerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BorrowerUpdate) SetUpdatedAt(v time.Time) *BorrowerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *BorrowerUpdate) SetName(v string) *BorrowerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableName(v *string) *BorrowerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *BorrowerUpdate) SetEmail(v string) *BorrowerUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableEmail(v *string) *BorrowerUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *BorrowerUpdate) SetPhone(v string) *BorrowerUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillablePhone(v *string) *BorrowerUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *BorrowerUpdate) ClearPhone() *BorrowerUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *BorrowerUpdate) SetOrganization(v string) *BorrowerUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableOrganization(v *string) *BorrowerUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *BorrowerUpdate) ClearOrganization() *BorrowerUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// SetStudentID sets the "student_id" field.
func (_u *BorrowerUpdate) SetStudentID(v string) *BorrowerUpdate {
	_u.mutation.SetStudentID(v)
	return _u
}

// SetNillableStudentID sets the "student_id" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableStudentID(v *string) *BorrowerUpdate {
	if v != nil {
		_u.SetStudentID(*v)
	}
	return _u
}

// ClearStudentID clears the value of the "student_id" field.
func (_u *BorrowerUpdate) ClearStudentID() *BorrowerUpdate {
	_u.mutation.ClearStudentID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BorrowerUpdate) SetNotes(v string) *BorrowerUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableNotes(v *string) *BorrowerUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BorrowerUpdate) ClearNotes() *BorrowerUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *BorrowerUpdate) SetIsActive(v bool) *BorrowerUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableIsActive(v *bool) *BorrowerUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSelfRegistered sets the "self_registered" field.
func (_u *BorrowerUpdate) SetSelfRegistered(v bool) *BorrowerUpdate {
	_u.mutation.SetSelfRegistered(v)
	return _u
}

// SetNillableSelfRegistered sets the "self_registered" field if the given value is not nil.
func (_u *BorrowerUpdate) SetNillableSelfRegistered(v *bool) *BorrowerUpdate {
	if v != nil {
		_u.SetSelfRegistered(*v)
	}
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *BorrowerUpdate) SetGroupID(id uuid.UUID) *BorrowerUpdate {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BorrowerUpdate) SetGroup(v *Group) *BorrowerUpdate {
	return _u.SetGroupID(v.ID)
}

// AddLoanIDs adds the "loans" edge to the Loan entity by IDs.
func (_u *BorrowerUpdate) AddLoanIDs(ids ...uuid.UUID) *BorrowerUpdate {
	_u.mutation.AddLoanIDs(ids...)
	return _u
}

// AddLoans adds the "loans" edges to the Loan entity.
func (_u *BorrowerUpdate) AddLoans(v ...*Loan) *BorrowerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLoanIDs(ids...)
}

// Mutation returns the BorrowerMutation object of the builder.
func (_u *BorrowerUpdate) Mutation() *BorrowerMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BorrowerUpdate) ClearGroup() *BorrowerUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearLoans clears all "loans" edges to the Loan entity.
func (_u *BorrowerUpdate) ClearLoans() *BorrowerUpdate {
	_u.mutation.ClearLoans()
	return _u
}

// RemoveLoanIDs removes the "loans" edge to Loan entities by IDs.
func (_u *BorrowerUpdate) RemoveLoanIDs(ids ...uuid.UUID) *BorrowerUpdate {
	_u.mutation.RemoveLoanIDs(ids...)
	return _u
}

// RemoveLoans removes "loans" edges to Loan entities.
func (_u *BorrowerUpdate) RemoveLoans(v ...*Loan) *BorrowerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLoanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BorrowerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BorrowerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BorrowerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BorrowerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BorrowerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := borrower.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BorrowerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := borrower.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Borrower.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := borrower.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Borrower.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := borrower.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Borrower.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Organization(); ok {
		if err := borrower.OrganizationValidator(v); err != nil {
			return &ValidationError{Name: "organization", err: fmt.Errorf(`ent: validator failed for field "Borrower.organization": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StudentID(); ok {
		if err := borrower.StudentIDValidator(v); err != nil {
			return &ValidationError{Name: "student_id", err: fmt.Errorf(`ent: validator failed for field "Borrower.student_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := borrower.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Borrower.notes": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Borrower.group"`)
	}
	return nil
}

func (_u *BorrowerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(borrower.Table, borrower.Columns, sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(borrower.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(borrower.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(borrower.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(borrower.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(borrower.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(borrower.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(borrower.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.StudentID(); ok {
		_spec.SetField(borrower.FieldStudentID, field.TypeString, value)
	}
	if _u.mutation.StudentIDCleared() {
		_spec.ClearField(borrower.FieldStudentID, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(borrower.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(borrower.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(borrower.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SelfRegistered(); ok {
		_spec.SetField(borrower.FieldSelfRegistered, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   borrower.GroupTable,
			Columns: []string{borrower.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   borrower.GroupTable,
			Columns: []string{borrower.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LoansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLoansIDs(); len(nodes) > 0 && !_u.mutation.LoansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{borrower.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BorrowerUpdateOne is the builder for updating a single Borrower entity.
type BorrowerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BorrowerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BorrowerUpdateOne) SetUpdatedAt(v time.Time) *BorrowerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *BorrowerUpdateOne) SetName(v string) *BorrowerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableName(v *string) *BorrowerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *BorrowerUpdateOne) SetEmail(v string) *BorrowerUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableEmail(v *string) *BorrowerUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *BorrowerUpdateOne) SetPhone(v string) *BorrowerUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillablePhone(v *string) *BorrowerUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *BorrowerUpdateOne) ClearPhone() *BorrowerUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *BorrowerUpdateOne) SetOrganization(v string) *BorrowerUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableOrganization(v *string) *BorrowerUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *BorrowerUpdateOne) ClearOrganization() *BorrowerUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// SetStudentID sets the "student_id" field.
func (_u *BorrowerUpdateOne) SetStudentID(v string) *BorrowerUpdateOne {
	_u.mutation.SetStudentID(v)
	return _u
}

// SetNillableStudentID sets the "student_id" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableStudentID(v *string) *BorrowerUpdateOne {
	if v != nil {
		_u.SetStudentID(*v)
	}
	return _u
}

// ClearStudentID clears the value of the "student_id" field.
func (_u *BorrowerUpdateOne) ClearStudentID() *BorrowerUpdateOne {
	_u.mutation.ClearStudentID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BorrowerUpdateOne) SetNotes(v string) *BorrowerUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableNotes(v *string) *BorrowerUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BorrowerUpdateOne) ClearNotes() *BorrowerUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *BorrowerUpdateOne) SetIsActive(v bool) *BorrowerUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableIsActive(v *bool) *BorrowerUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSelfRegistered sets the "self_registered" field.
func (_u *BorrowerUpdateOne) SetSelfRegistered(v bool) *BorrowerUpdateOne {
	_u.mutation.SetSelfRegistered(v)
	return _u
}

// SetNillableSelfRegistered sets the "self_registered" field if the given value is not nil.
func (_u *BorrowerUpdateOne) SetNillableSelfRegistered(v *bool) *BorrowerUpdateOne {
	if v != nil {
		_u.SetSelfRegistered(*v)
	}
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *BorrowerUpdateOne) SetGroupID(id uuid.UUID) *BorrowerUpdateOne {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BorrowerUpdateOne) SetGroup(v *Group) *BorrowerUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddLoanIDs adds the "loans" edge to the Loan entity by IDs.
func (_u *BorrowerUpdateOne) AddLoanIDs(ids ...uuid.UUID) *BorrowerUpdateOne {
	_u.mutation.AddLoanIDs(ids...)
	return _u
}

// AddLoans adds the "loans" edges to the Loan entity.
func (_u *BorrowerUpdateOne) AddLoans(v ...*Loan) *BorrowerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLoanIDs(ids...)
}

// Mutation returns the BorrowerMutation object of the builder.
func (_u *BorrowerUpdateOne) Mutation() *BorrowerMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BorrowerUpdateOne) ClearGroup() *BorrowerUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearLoans clears all "loans" edges to the Loan entity.
func (_u *BorrowerUpdateOne) ClearLoans() *BorrowerUpdateOne {
	_u.mutation.ClearLoans()
	return _u
}

// RemoveLoanIDs removes the "loans" edge to Loan entities by IDs.
func (_u *BorrowerUpdateOne) RemoveLoanIDs(ids ...uuid.UUID) *BorrowerUpdateOne {
	_u.mutation.RemoveLoanIDs(ids...)
	return _u
}

// RemoveLoans removes "loans" edges to Loan entities.
func (_u *BorrowerUpdateOne) RemoveLoans(v ...*Loan) *BorrowerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLoanIDs(ids...)
}

// Where appends a list predicates to the BorrowerUpdate builder.
func (_u *BorrowerUpdateOne) Where(ps ...predicate.Borrower) *BorrowerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BorrowerUpdateOne) Select(field string, fields ...string) *BorrowerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Borrower entity.
func (_u *BorrowerUpdateOne) Save(ctx context.Context) (*Borrower, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BorrowerUpdateOne) SaveX(ctx context.Context) *Borrower {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BorrowerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BorrowerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BorrowerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := borrower.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BorrowerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := borrower.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Borrower.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := borrower.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Borrower.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := borrower.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Borrower.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Organization(); ok {
		if err := borrower.OrganizationValidator(v); err != nil {
			return &ValidationError{Name: "organization", err: fmt.Errorf(`ent: validator failed for field "Borrower.organization": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StudentID(); ok {
		if err := borrower.StudentIDValidator(v); err != nil {
			return &ValidationError{Name: "student_id", err: fmt.Errorf(`ent: validator failed for field "Borrower.student_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := borrower.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Borrower.notes": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Borrower.group"`)
	}
	return nil
}

func (_u *BorrowerUpdateOne) sqlSave(ctx context.Context) (_node *Borrower, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(borrower.Table, borrower.Columns, sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Borrower.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, borrower.FieldID)
		for _, f := range fields {
			if !borrower.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != borrower.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(borrower.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(borrower.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(borrower.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(borrower.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(borrower.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(borrower.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(borrower.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.StudentID(); ok {
		_spec.SetField(borrower.FieldStudentID, field.TypeString, value)
	}
	if _u.mutation.StudentIDCleared() {
		_spec.ClearField(borrower.FieldStudentID, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(borrower.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(borrower.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(borrower.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SelfRegistered(); ok {
		_spec.SetField(borrower.FieldSelfRegistered, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   borrower.GroupTable,
			Columns: []string{borrower.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   borrower.GroupTable,
			Columns: []string{borrower.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LoansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLoansIDs(); len(nodes) > 0 && !_u.mutation.LoansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Borrower{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{borrower.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
