// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/loan"
)

// BorrowerCreate is the builder for creating a Borrower entity.
type BorrowerCreate struct {
	config
	mutation *BorrowerMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *BorrowerCreate) SetCreatedAt(v time.Time) *BorrowerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableCreatedAt(v *time.Time) *BorrowerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BorrowerCreate) SetUpdatedAt(v time.Time) *BorrowerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableUpdatedAt(v *time.Time) *BorrowerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *BorrowerCreate) SetName(v string) *BorrowerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *BorrowerCreate) SetEmail(v string) *BorrowerCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *BorrowerCreate) SetPhone(v string) *BorrowerCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillablePhone(v *string) *BorrowerCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetOrganization sets the "organization" field.
func (_c *BorrowerCreate) SetOrganization(v string) *BorrowerCreate {
	_c.mutation.SetOrganization(v)
	return _c
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableOrganization(v *string) *BorrowerCreate {
	if v != nil {
		_c.SetOrganization(*v)
	}
	return _c
}

// SetStudentID sets the "student_id" field.
func (_c *BorrowerCreate) SetStudentID(v string) *BorrowerCreate {
	_c.mutation.SetStudentID(v)
	return _c
}

// SetNillableStudentID sets the "student_id" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableStudentID(v *string) *BorrowerCreate {
	if v != nil {
		_c.SetStudentID(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *BorrowerCreate) SetNotes(v string) *BorrowerCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableNotes(v *string) *BorrowerCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *BorrowerCreate) SetIsActive(v bool) *BorrowerCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableIsActive(v *bool) *BorrowerCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetSelfRegistered sets the "self_registered" field.
func (_c *BorrowerCreate) SetSelfRegistered(v bool) *BorrowerCreate {
	_c.mutation.SetSelfRegistered(v)
	return _c
}

// SetNillableSelfRegistered sets the "self_registered" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableSelfRegistered(v *bool) *BorrowerCreate {
	if v != nil {
		_c.SetSelfRegistered(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BorrowerCreate) SetID(v uuid.UUID) *BorrowerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BorrowerCreate) SetNillableID(v *uuid.UUID) *BorrowerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_c *BorrowerCreate) SetGroupID(id uuid.UUID) *BorrowerCreate {
	_c.mutation.SetGroupID(id)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *BorrowerCreate) SetGroup(v *Group) *BorrowerCreate {
	return _c.SetGroupID(v.ID)
}

// AddLoanIDs adds the "loans" edge to the Loan entity by IDs.
func (_c *BorrowerCreate) AddLoanIDs(ids ...uuid.UUID) *BorrowerCreate {
	_c.mutation.AddLoanIDs(ids...)
	return _c
}

// AddLoans adds the "loans" edges to the Loan entity.
func (_c *BorrowerCreate) AddLoans(v ...*Loan) *BorrowerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLoanIDs(ids...)
}

// Mutation returns the BorrowerMutation object of the builder.
func (_c *BorrowerCreate) Mutation() *BorrowerMutation {
	return _c.mutation
}

// Save creates the Borrower in the database.
func (_c *BorrowerCreate) Save(ctx context.Context) (*Borrower, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BorrowerCreate) SaveX(ctx context.Context) *Borrower {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BorrowerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BorrowerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BorrowerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := borrower.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := borrower.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := borrower.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.SelfRegistered(); !ok {
		v := borrower.DefaultSelfRegistered
		_c.mutation.SetSelfRegistered(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := borrower.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BorrowerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Borrower.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Borrower.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Borrower.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := borrower.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Borrower.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Borrower.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := borrower.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Borrower.email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := borrower.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Borrower.phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Organization(); ok {
		if err := borrower.OrganizationValidator(v); err != nil {
			return &ValidationError{Name: "organization", err: fmt.Errorf(`ent: validator failed for field "Borrower.organization": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StudentID(); ok {
		if err := borrower.StudentIDValidator(v); err != nil {
			return &ValidationError{Name: "student_id", err: fmt.Errorf(`ent: validator failed for field "Borrower.student_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Notes(); ok {
		if err := borrower.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Borrower.notes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Borrower.is_active"`)}
	}
	if _, ok := _c.mutation.SelfRegistered(); !ok {
		return &ValidationError{Name: "self_registered", err: errors.New(`ent: missing required field "Borrower.self_registered"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Borrower.group"`)}
	}
	return nil
}

func (_c *BorrowerCreate) sqlSave(ctx context.Context) (*Borrower, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BorrowerCreate) createSpec() (*Borrower, *sqlgraph.CreateSpec) {
	var (
		_node = &Borrower{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(borrower.Table, sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(borrower.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(borrower.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(borrower.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(borrower.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(borrower.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Organization(); ok {
		_spec.SetField(borrower.FieldOrganization, field.TypeString, value)
		_node.Organization = value
	}
	if value, ok := _c.mutation.StudentID(); ok {
		_spec.SetField(borrower.FieldStudentID, field.TypeString, value)
		_node.StudentID = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(borrower.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(borrower.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.SelfRegistered(); ok {
		_spec.SetField(borrower.FieldSelfRegistered, field.TypeBool, value)
		_node.SelfRegistered = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   borrower.GroupTable,
			Columns: []string{borrower.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_borrowers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LoansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrower.LoansTable,
			Columns: []string{borrower.LoansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BorrowerCreateBulk is the builder for creating many Borrower entities in bulk.
type BorrowerCreateBulk struct {
	config
	err      error
	builders []*BorrowerCreate
}

// Save creates the Borrower entities in the database.
func (_c *BorrowerCreateBulk) Save(ctx context.Context) ([]*Borrower, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Borrower, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BorrowerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BorrowerCreateBulk) SaveX(ctx context.Context) []*Borrower {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BorrowerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BorrowerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
