// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// Borrower is the model entity for the Borrower schema.
type Borrower struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Full name of the borrower
	Name string `json:"name,omitempty"`
	// Contact email address
	Email string `json:"email,omitempty"`
	// Contact phone number
	Phone string `json:"phone,omitempty"`
	// Company or startup name
	Organization string `json:"organization,omitempty"`
	// University student ID
	StudentID string `json:"student_id,omitempty"`
	// Additional notes about the borrower
	Notes string `json:"notes,omitempty"`
	// Whether borrower can currently check out equipment
	IsActive bool `json:"is_active,omitempty"`
	// Whether borrower registered themselves via kiosk self-service
	SelfRegistered bool `json:"self_registered,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BorrowerQuery when eager-loading is set.
	Edges           BorrowerEdges `json:"edges"`
	group_borrowers *uuid.UUID
	selectValues    sql.SelectValues
}

// BorrowerEdges holds the relations/edges for other nodes in the graph.
type BorrowerEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Loans holds the value of the loans edge.
	Loans []*Loan `json:"loans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BorrowerEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// LoansOrErr returns the Loans value or an error if the edge
// was not loaded in eager-loading.
func (e BorrowerEdges) LoansOrErr() ([]*Loan, error) {
	if e.loadedTypes[1] {
		return e.Loans, nil
	}
	return nil, &NotLoadedError{edge: "loans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Borrower) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case borrower.FieldIsActive, borrower.FieldSelfRegistered:
			values[i] = new(sql.NullBool)
		case borrower.FieldName, borrower.FieldEmail, borrower.FieldPhone, borrower.FieldOrganization, borrower.FieldStudentID, borrower.FieldNotes:
			values[i] = new(sql.NullString)
		case borrower.FieldCreatedAt, borrower.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case borrower.FieldID:
			values[i] = new(uuid.UUID)
		case borrower.ForeignKeys[0]: // group_borrowers
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Borrower fields.
func (_m *Borrower) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case borrower.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case borrower.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case borrower.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case borrower.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case borrower.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case borrower.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case borrower.FieldOrganization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization", values[i])
			} else if value.Valid {
				_m.Organization = value.String
			}
		case borrower.FieldStudentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field student_id", values[i])
			} else if value.Valid {
				_m.StudentID = value.String
			}
		case borrower.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case borrower.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case borrower.FieldSelfRegistered:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field self_registered", values[i])
			} else if value.Valid {
				_m.SelfRegistered = value.Bool
			}
		case borrower.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_borrowers", values[i])
			} else if value.Valid {
				_m.group_borrowers = new(uuid.UUID)
				*_m.group_borrowers = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Borrower.
// This includes values selected through modifiers, order, etc.
func (_m *Borrower) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the Borrower entity.
func (_m *Borrower) QueryGroup() *GroupQuery {
	return NewBorrowerClient(_m.config).QueryGroup(_m)
}

// QueryLoans queries the "loans" edge of the Borrower entity.
func (_m *Borrower) QueryLoans() *LoanQuery {
	return NewBorrowerClient(_m.config).QueryLoans(_m)
}

// Update returns a builder for updating this Borrower.
// Note that you need to call Borrower.Unwrap() before calling this method if this Borrower
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Borrower) Update() *BorrowerUpdateOne {
	return NewBorrowerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Borrower entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Borrower) Unwrap() *Borrower {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Borrower is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Borrower) String() string {
	var builder strings.Builder
	builder.WriteString("Borrower(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("organization=")
	builder.WriteString(_m.Organization)
	builder.WriteString(", ")
	builder.WriteString("student_id=")
	builder.WriteString(_m.StudentID)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("self_registered=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelfRegistered))
	builder.WriteByte(')')
	return builder.String()
}

// Borrowers is a parsable slice of Borrower.
type Borrowers []*Borrower
