// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/kiosksession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// KioskSession is the model entity for the KioskSession schema.
type KioskSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Whether kiosk mode is currently active
	IsActive bool `json:"is_active,omitempty"`
	// When the temporary admin unlock expires (null = locked)
	UnlockedUntil *time.Time `json:"unlocked_until,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KioskSessionQuery when eager-loading is set.
	Edges              KioskSessionEdges `json:"edges"`
	user_kiosk_session *uuid.UUID
	selectValues       sql.SelectValues
}

// KioskSessionEdges holds the relations/edges for other nodes in the graph.
type KioskSessionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KioskSessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KioskSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kiosksession.FieldIsActive:
			values[i] = new(sql.NullBool)
		case kiosksession.FieldCreatedAt, kiosksession.FieldUpdatedAt, kiosksession.FieldUnlockedUntil:
			values[i] = new(sql.NullTime)
		case kiosksession.FieldID:
			values[i] = new(uuid.UUID)
		case kiosksession.ForeignKeys[0]: // user_kiosk_session
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KioskSession fields.
func (_m *KioskSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kiosksession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case kiosksession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case kiosksession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case kiosksession.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case kiosksession.FieldUnlockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field unlocked_until", values[i])
			} else if value.Valid {
				_m.UnlockedUntil = new(time.Time)
				*_m.UnlockedUntil = value.Time
			}
		case kiosksession.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_kiosk_session", values[i])
			} else if value.Valid {
				_m.user_kiosk_session = new(uuid.UUID)
				*_m.user_kiosk_session = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KioskSession.
// This includes values selected through modifiers, order, etc.
func (_m *KioskSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the KioskSession entity.
func (_m *KioskSession) QueryUser() *UserQuery {
	return NewKioskSessionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this KioskSession.
// Note that you need to call KioskSession.Unwrap() before calling this method if this KioskSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KioskSession) Update() *KioskSessionUpdateOne {
	return NewKioskSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KioskSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KioskSession) Unwrap() *KioskSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KioskSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KioskSession) String() string {
	var builder strings.Builder
	builder.WriteString("KioskSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.UnlockedUntil; v != nil {
		builder.WriteString("unlocked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// KioskSessions is a parsable slice of KioskSession.
type KioskSessions []*KioskSession
