// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/kiosksession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// KioskSessionCreate is the builder for creating a KioskSession entity.
type KioskSessionCreate struct {
	config
	mutation *KioskSessionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *KioskSessionCreate) SetCreatedAt(v time.Time) *KioskSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KioskSessionCreate) SetNillableCreatedAt(v *time.Time) *KioskSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KioskSessionCreate) SetUpdatedAt(v time.Time) *KioskSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KioskSessionCreate) SetNillableUpdatedAt(v *time.Time) *KioskSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *KioskSessionCreate) SetIsActive(v bool) *KioskSessionCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *KioskSessionCreate) SetNillableIsActive(v *bool) *KioskSessionCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetUnlockedUntil sets the "unlocked_until" field.
func (_c *KioskSessionCreate) SetUnlockedUntil(v time.Time) *KioskSessionCreate {
	_c.mutation.SetUnlockedUntil(v)
	return _c
}

// SetNillableUnlockedUntil sets the "unlocked_until" field if the given value is not nil.
func (_c *KioskSessionCreate) SetNillableUnlockedUntil(v *time.Time) *KioskSessionCreate {
	if v != nil {
		_c.SetUnlockedUntil(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KioskSessionCreate) SetID(v uuid.UUID) *KioskSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KioskSessionCreate) SetNillableID(v *uuid.UUID) *KioskSessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *KioskSessionCreate) SetUserID(id uuid.UUID) *KioskSessionCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *KioskSessionCreate) SetUser(v *User) *KioskSessionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the KioskSessionMutation object of the builder.
func (_c *KioskSessionCreate) Mutation() *KioskSessionMutation {
	return _c.mutation
}

// Save creates the KioskSession in the database.
func (_c *KioskSessionCreate) Save(ctx context.Context) (*KioskSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KioskSessionCreate) SaveX(ctx context.Context) *KioskSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KioskSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KioskSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KioskSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := kiosksession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := kiosksession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := kiosksession.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := kiosksession.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KioskSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KioskSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "KioskSession.updated_at"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "KioskSession.is_active"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "KioskSession.user"`)}
	}
	return nil
}

func (_c *KioskSessionCreate) sqlSave(ctx context.Context) (*KioskSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KioskSessionCreate) createSpec() (*KioskSession, *sqlgraph.CreateSpec) {
	var (
		_node = &KioskSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(kiosksession.Table, sqlgraph.NewFieldSpec(kiosksession.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(kiosksession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(kiosksession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(kiosksession.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.UnlockedUntil(); ok {
		_spec.SetField(kiosksession.FieldUnlockedUntil, field.TypeTime, value)
		_node.UnlockedUntil = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   kiosksession.UserTable,
			Columns: []string{kiosksession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_kiosk_session = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// KioskSessionCreateBulk is the builder for creating many KioskSession entities in bulk.
type KioskSessionCreateBulk struct {
	config
	err      error
	builders []*KioskSessionCreate
}

// Save creates the KioskSession entities in the database.
func (_c *KioskSessionCreateBulk) Save(ctx context.Context) ([]*KioskSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KioskSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KioskSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KioskSessionCreateBulk) SaveX(ctx context.Context) []*KioskSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KioskSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KioskSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
