// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/kiosksession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// KioskSessionUpdate is the builder for updating KioskSession entities.
type KioskSessionUpdate struct {
	config
	hooks    []Hook
	mutation *KioskSessionMutation
}

// Where appends a list predicates to the KioskSessionUpdate builder.
func (_u *KioskSessionUpdate) Where(ps ...predicate.KioskSession) *KioskSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KioskSessionUpdate) SetUpdatedAt(v time.Time) *KioskSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *KioskSessionUpdate) SetIsActive(v bool) *KioskSessionUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *KioskSessionUpdate) SetNillableIsActive(v *bool) *KioskSessionUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUnlockedUntil sets the "unlocked_until" field.
func (_u *KioskSessionUpdate) SetUnlockedUntil(v time.Time) *KioskSessionUpdate {
	_u.mutation.SetUnlockedUntil(v)
	return _u
}

// SetNillableUnlockedUntil sets the "unlocked_until" field if the given value is not nil.
func (_u *KioskSessionUpdate) SetNillableUnlockedUntil(v *time.Time) *KioskSessionUpdate {
	if v != nil {
		_u.SetUnlockedUntil(*v)
	}
	return _u
}

// ClearUnlockedUntil clears the value of the "unlocked_until" field.
func (_u *KioskSessionUpdate) ClearUnlockedUntil() *KioskSessionUpdate {
	_u.mutation.ClearUnlockedUntil()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *KioskSessionUpdate) SetUserID(id uuid.UUID) *KioskSessionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *KioskSessionUpdate) SetUser(v *User) *KioskSessionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the KioskSessionMutation object of the builder.
func (_u *KioskSessionUpdate) Mutation() *KioskSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *KioskSessionUpdate) ClearUser() *KioskSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KioskSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KioskSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KioskSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KioskSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KioskSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kiosksession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KioskSessionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KioskSession.user"`)
	}
	return nil
}

func (_u *KioskSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kiosksession.Table, kiosksession.Columns, sqlgraph.NewFieldSpec(kiosksession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kiosksession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(kiosksession.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UnlockedUntil(); ok {
		_spec.SetField(kiosksession.FieldUnlockedUntil, field.TypeTime, value)
	}
	if _u.mutation.UnlockedUntilCleared() {
		_spec.ClearField(kiosksession.FieldUnlockedUntil, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   kiosksession.UserTable,
			Columns: []string{kiosksession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   kiosksession.UserTable,
			Columns: []string{kiosksession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kiosksession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KioskSessionUpdateOne is the builder for updating a single KioskSession entity.
type KioskSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KioskSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KioskSessionUpdateOne) SetUpdatedAt(v time.Time) *KioskSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *KioskSessionUpdateOne) SetIsActive(v bool) *KioskSessionUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *KioskSessionUpdateOne) SetNillableIsActive(v *bool) *KioskSessionUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUnlockedUntil sets the "unlocked_until" field.
func (_u *KioskSessionUpdateOne) SetUnlockedUntil(v time.Time) *KioskSessionUpdateOne {
	_u.mutation.SetUnlockedUntil(v)
	return _u
}

// SetNillableUnlockedUntil sets the "unlocked_until" field if the given value is not nil.
func (_u *KioskSessionUpdateOne) SetNillableUnlockedUntil(v *time.Time) *KioskSessionUpdateOne {
	if v != nil {
		_u.SetUnlockedUntil(*v)
	}
	return _u
}

// ClearUnlockedUntil clears the value of the "unlocked_until" field.
func (_u *KioskSessionUpdateOne) ClearUnlockedUntil() *KioskSessionUpdateOne {
	_u.mutation.ClearUnlockedUntil()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *KioskSessionUpdateOne) SetUserID(id uuid.UUID) *KioskSessionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *KioskSessionUpdateOne) SetUser(v *User) *KioskSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the KioskSessionMutation object of the builder.
func (_u *KioskSessionUpdateOne) Mutation() *KioskSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *KioskSessionUpdateOne) ClearUser() *KioskSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the KioskSessionUpdate builder.
func (_u *KioskSessionUpdateOne) Where(ps ...predicate.KioskSession) *KioskSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KioskSessionUpdateOne) Select(field string, fields ...string) *KioskSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KioskSession entity.
func (_u *KioskSessionUpdateOne) Save(ctx context.Context) (*KioskSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KioskSessionUpdateOne) SaveX(ctx context.Context) *KioskSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KioskSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KioskSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KioskSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kiosksession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KioskSessionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KioskSession.user"`)
	}
	return nil
}

func (_u *KioskSessionUpdateOne) sqlSave(ctx context.Context) (_node *KioskSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kiosksession.Table, kiosksession.Columns, sqlgraph.NewFieldSpec(kiosksession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KioskSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kiosksession.FieldID)
		for _, f := range fields {
			if !kiosksession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kiosksession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kiosksession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(kiosksession.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UnlockedUntil(); ok {
		_spec.SetField(kiosksession.FieldUnlockedUntil, field.TypeTime, value)
	}
	if _u.mutation.UnlockedUntilCleared() {
		_spec.ClearField(kiosksession.FieldUnlockedUntil, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   kiosksession.UserTable,
			Columns: []string{kiosksession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   kiosksession.UserTable,
			Columns: []string{kiosksession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KioskSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kiosksession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
