// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/loan"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// LoanQuery is the builder for querying Loan entities.
type LoanQuery struct {
	config
	ctx              *QueryContext
	order            []loan.OrderOption
	inters           []Interceptor
	predicates       []predicate.Loan
	withGroup        *GroupQuery
	withItem         *ItemQuery
	withBorrower     *BorrowerQuery
	withCheckedOutBy *UserQuery
	withReturnedBy   *UserQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoanQuery builder.
func (_q *LoanQuery) Where(ps ...predicate.Loan) *LoanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LoanQuery) Limit(limit int) *LoanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LoanQuery) Offset(offset int) *LoanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LoanQuery) Unique(unique bool) *LoanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LoanQuery) Order(o ...loan.OrderOption) *LoanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *LoanQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loan.Table, loan.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loan.GroupTable, loan.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItem chains the current query on the "item" edge.
func (_q *LoanQuery) QueryItem() *ItemQuery {
	query := (&ItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loan.Table, loan.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loan.ItemTable, loan.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBorrower chains the current query on the "borrower" edge.
func (_q *LoanQuery) QueryBorrower() *BorrowerQuery {
	query := (&BorrowerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loan.Table, loan.FieldID, selector),
			sqlgraph.To(borrower.Table, borrower.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loan.BorrowerTable, loan.BorrowerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCheckedOutBy chains the current query on the "checked_out_by" edge.
func (_q *LoanQuery) QueryCheckedOutBy() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loan.Table, loan.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loan.CheckedOutByTable, loan.CheckedOutByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReturnedBy chains the current query on the "returned_by" edge.
func (_q *LoanQuery) QueryReturnedBy() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loan.Table, loan.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loan.ReturnedByTable, loan.ReturnedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Loan entity from the query.
// Returns a *NotFoundError when no Loan was found.
func (_q *LoanQuery) First(ctx context.Context) (*Loan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LoanQuery) FirstX(ctx context.Context) *Loan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Loan ID from the query.
// Returns a *NotFoundError when no Loan ID was found.
func (_q *LoanQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LoanQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Loan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Loan entity is found.
// Returns a *NotFoundError when no Loan entities are found.
func (_q *LoanQuery) Only(ctx context.Context) (*Loan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loan.Label}
	default:
		return nil, &NotSingularError{loan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LoanQuery) OnlyX(ctx context.Context) *Loan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Loan ID in the query.
// Returns a *NotSingularError when more than one Loan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LoanQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loan.Label}
	default:
		err = &NotSingularError{loan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LoanQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Loans.
func (_q *LoanQuery) All(ctx context.Context) ([]*Loan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Loan, *LoanQuery]()
	return withInterceptors[[]*Loan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LoanQuery) AllX(ctx context.Context) []*Loan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Loan IDs.
func (_q *LoanQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(loan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LoanQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LoanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LoanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LoanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LoanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LoanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LoanQuery) Clone() *LoanQuery {
	if _q == nil {
		return nil
	}
	return &LoanQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]loan.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Loan{}, _q.predicates...),
		withGroup:        _q.withGroup.Clone(),
		withItem:         _q.withItem.Clone(),
		withBorrower:     _q.withBorrower.Clone(),
		withCheckedOutBy: _q.withCheckedOutBy.Clone(),
		withReturnedBy:   _q.withReturnedBy.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LoanQuery) WithGroup(opts ...func(*GroupQuery)) *LoanQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LoanQuery) WithItem(opts ...func(*ItemQuery)) *LoanQuery {
	query := (&ItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withItem = query
	return _q
}

// WithBorrower tells the query-builder to eager-load the nodes that are connected to
// the "borrower" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LoanQuery) WithBorrower(opts ...func(*BorrowerQuery)) *LoanQuery {
	query := (&BorrowerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBorrower = query
	return _q
}

// WithCheckedOutBy tells the query-builder to eager-load the nodes that are connected to
// the "checked_out_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LoanQuery) WithCheckedOutBy(opts ...func(*UserQuery)) *LoanQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCheckedOutBy = query
	return _q
}

// WithReturnedBy tells the query-builder to eager-load the nodes that are connected to
// the "returned_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LoanQuery) WithReturnedBy(opts ...func(*UserQuery)) *LoanQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReturnedBy = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Loan.Query().
//		GroupBy(loan.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LoanQuery) GroupBy(field string, fields ...string) *LoanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LoanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = loan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Loan.Query().
//		Select(loan.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *LoanQuery) Select(fields ...string) *LoanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LoanSelect{LoanQuery: _q}
	sbuild.label = loan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LoanSelect configured with the given aggregations.
func (_q *LoanQuery) Aggregate(fns ...AggregateFunc) *LoanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LoanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !loan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LoanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Loan, error) {
	var (
		nodes       = []*Loan{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withGroup != nil,
			_q.withItem != nil,
			_q.withBorrower != nil,
			_q.withCheckedOutBy != nil,
			_q.withReturnedBy != nil,
		}
	)
	if _q.withGroup != nil || _q.withItem != nil || _q.withBorrower != nil || _q.withCheckedOutBy != nil || _q.withReturnedBy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, loan.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Loan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Loan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *Loan, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withItem; query != nil {
		if err := _q.loadItem(ctx, query, nodes, nil,
			func(n *Loan, e *Item) { n.Edges.Item = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBorrower; query != nil {
		if err := _q.loadBorrower(ctx, query, nodes, nil,
			func(n *Loan, e *Borrower) { n.Edges.Borrower = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCheckedOutBy; query != nil {
		if err := _q.loadCheckedOutBy(ctx, query, nodes, nil,
			func(n *Loan, e *User) { n.Edges.CheckedOutBy = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReturnedBy; query != nil {
		if err := _q.loadReturnedBy(ctx, query, nodes, nil,
			func(n *Loan, e *User) { n.Edges.ReturnedBy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LoanQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*Loan, init func(*Loan), assign func(*Loan, *Group)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Loan)
	for i := range nodes {
		if nodes[i].group_loans == nil {
			continue
		}
		fk := *nodes[i].group_loans
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_loans" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LoanQuery) loadItem(ctx context.Context, query *ItemQuery, nodes []*Loan, init func(*Loan), assign func(*Loan, *Item)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Loan)
	for i := range nodes {
		if nodes[i].item_loans == nil {
			continue
		}
		fk := *nodes[i].item_loans
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(item.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "item_loans" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LoanQuery) loadBorrower(ctx context.Context, query *BorrowerQuery, nodes []*Loan, init func(*Loan), assign func(*Loan, *Borrower)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Loan)
	for i := range nodes {
		if nodes[i].borrower_loans == nil {
			continue
		}
		fk := *nodes[i].borrower_loans
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(borrower.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "borrower_loans" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LoanQuery) loadCheckedOutBy(ctx context.Context, query *UserQuery, nodes []*Loan, init func(*Loan), assign func(*Loan, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Loan)
	for i := range nodes {
		if nodes[i].user_checkouts == nil {
			continue
		}
		fk := *nodes[i].user_checkouts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_checkouts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LoanQuery) loadReturnedBy(ctx context.Context, query *UserQuery, nodes []*Loan, init func(*Loan), assign func(*Loan, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Loan)
	for i := range nodes {
		if nodes[i].user_returns == nil {
			continue
		}
		fk := *nodes[i].user_returns
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_returns" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *LoanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LoanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(loan.Table, loan.Columns, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loan.FieldID)
		for i := range fields {
			if fields[i] != loan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LoanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(loan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = loan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoanGroupBy is the group-by builder for Loan entities.
type LoanGroupBy struct {
	selector
	build *LoanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LoanGroupBy) Aggregate(fns ...AggregateFunc) *LoanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LoanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoanQuery, *LoanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LoanGroupBy) sqlScan(ctx context.Context, root *LoanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LoanSelect is the builder for selecting fields of Loan entities.
type LoanSelect struct {
	*LoanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LoanSelect) Aggregate(fns ...AggregateFunc) *LoanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LoanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoanQuery, *LoanSelect](ctx, _s.LoanQuery, _s, _s.inters, v)
}

func (_s *LoanSelect) sqlScan(ctx context.Context, root *LoanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
