// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/loan"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// LoanCreate is the builder for creating a Loan entity.
type LoanCreate struct {
	config
	mutation *LoanMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LoanCreate) SetCreatedAt(v time.Time) *LoanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LoanCreate) SetNillableCreatedAt(v *time.Time) *LoanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LoanCreate) SetUpdatedAt(v time.Time) *LoanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LoanCreate) SetNillableUpdatedAt(v *time.Time) *LoanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (_c *LoanCreate) SetCheckedOutAt(v time.Time) *LoanCreate {
	_c.mutation.SetCheckedOutAt(v)
	return _c
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (_c *LoanCreate) SetNillableCheckedOutAt(v *time.Time) *LoanCreate {
	if v != nil {
		_c.SetCheckedOutAt(*v)
	}
	return _c
}

// SetDueAt sets the "due_at" field.
func (_c *LoanCreate) SetDueAt(v time.Time) *LoanCreate {
	_c.mutation.SetDueAt(v)
	return _c
}

// SetReturnedAt sets the "returned_at" field.
func (_c *LoanCreate) SetReturnedAt(v time.Time) *LoanCreate {
	_c.mutation.SetReturnedAt(v)
	return _c
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (_c *LoanCreate) SetNillableReturnedAt(v *time.Time) *LoanCreate {
	if v != nil {
		_c.SetReturnedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *LoanCreate) SetNotes(v string) *LoanCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *LoanCreate) SetNillableNotes(v *string) *LoanCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetReturnNotes sets the "return_notes" field.
func (_c *LoanCreate) SetReturnNotes(v string) *LoanCreate {
	_c.mutation.SetReturnNotes(v)
	return _c
}

// SetNillableReturnNotes sets the "return_notes" field if the given value is not nil.
func (_c *LoanCreate) SetNillableReturnNotes(v *string) *LoanCreate {
	if v != nil {
		_c.SetReturnNotes(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *LoanCreate) SetQuantity(v int) *LoanCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *LoanCreate) SetNillableQuantity(v *int) *LoanCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LoanCreate) SetID(v uuid.UUID) *LoanCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LoanCreate) SetNillableID(v *uuid.UUID) *LoanCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_c *LoanCreate) SetGroupID(id uuid.UUID) *LoanCreate {
	_c.mutation.SetGroupID(id)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *LoanCreate) SetGroup(v *Group) *LoanCreate {
	return _c.SetGroupID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_c *LoanCreate) SetItemID(id uuid.UUID) *LoanCreate {
	_c.mutation.SetItemID(id)
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *LoanCreate) SetItem(v *Item) *LoanCreate {
	return _c.SetItemID(v.ID)
}

// SetBorrowerID sets the "borrower" edge to the Borrower entity by ID.
func (_c *LoanCreate) SetBorrowerID(id uuid.UUID) *LoanCreate {
	_c.mutation.SetBorrowerID(id)
	return _c
}

// SetBorrower sets the "borrower" edge to the Borrower entity.
func (_c *LoanCreate) SetBorrower(v *Borrower) *LoanCreate {
	return _c.SetBorrowerID(v.ID)
}

// SetCheckedOutByID sets the "checked_out_by" edge to the User entity by ID.
func (_c *LoanCreate) SetCheckedOutByID(id uuid.UUID) *LoanCreate {
	_c.mutation.SetCheckedOutByID(id)
	return _c
}

// SetNillableCheckedOutByID sets the "checked_out_by" edge to the User entity by ID if the given value is not nil.
func (_c *LoanCreate) SetNillableCheckedOutByID(id *uuid.UUID) *LoanCreate {
	if id != nil {
		_c = _c.SetCheckedOutByID(*id)
	}
	return _c
}

// SetCheckedOutBy sets the "checked_out_by" edge to the User entity.
func (_c *LoanCreate) SetCheckedOutBy(v *User) *LoanCreate {
	return _c.SetCheckedOutByID(v.ID)
}

// SetReturnedByID sets the "returned_by" edge to the User entity by ID.
func (_c *LoanCreate) SetReturnedByID(id uuid.UUID) *LoanCreate {
	_c.mutation.SetReturnedByID(id)
	return _c
}

// SetNillableReturnedByID sets the "returned_by" edge to the User entity by ID if the given value is not nil.
func (_c *LoanCreate) SetNillableReturnedByID(id *uuid.UUID) *LoanCreate {
	if id != nil {
		_c = _c.SetReturnedByID(*id)
	}
	return _c
}

// SetReturnedBy sets the "returned_by" edge to the User entity.
func (_c *LoanCreate) SetReturnedBy(v *User) *LoanCreate {
	return _c.SetReturnedByID(v.ID)
}

// Mutation returns the LoanMutation object of the builder.
func (_c *LoanCreate) Mutation() *LoanMutation {
	return _c.mutation
}

// Save creates the Loan in the database.
func (_c *LoanCreate) Save(ctx context.Context) (*Loan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoanCreate) SaveX(ctx context.Context) *Loan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := loan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := loan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CheckedOutAt(); !ok {
		v := loan.DefaultCheckedOutAt()
		_c.mutation.SetCheckedOutAt(v)
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		v := loan.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := loan.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Loan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Loan.updated_at"`)}
	}
	if _, ok := _c.mutation.CheckedOutAt(); !ok {
		return &ValidationError{Name: "checked_out_at", err: errors.New(`ent: missing required field "Loan.checked_out_at"`)}
	}
	if _, ok := _c.mutation.DueAt(); !ok {
		return &ValidationError{Name: "due_at", err: errors.New(`ent: missing required field "Loan.due_at"`)}
	}
	if v, ok := _c.mutation.Notes(); ok {
		if err := loan.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Loan.notes": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReturnNotes(); ok {
		if err := loan.ReturnNotesValidator(v); err != nil {
			return &ValidationError{Name: "return_notes", err: fmt.Errorf(`ent: validator failed for field "Loan.return_notes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Loan.quantity"`)}
	}
	if v, ok := _c.mutation.Quantity(); ok {
		if err := loan.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Loan.quantity": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Loan.group"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "Loan.item"`)}
	}
	if len(_c.mutation.BorrowerIDs()) == 0 {
		return &ValidationError{Name: "borrower", err: errors.New(`ent: missing required edge "Loan.borrower"`)}
	}
	return nil
}

func (_c *LoanCreate) sqlSave(ctx context.Context) (*Loan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoanCreate) createSpec() (*Loan, *sqlgraph.CreateSpec) {
	var (
		_node = &Loan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loan.Table, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(loan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(loan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CheckedOutAt(); ok {
		_spec.SetField(loan.FieldCheckedOutAt, field.TypeTime, value)
		_node.CheckedOutAt = value
	}
	if value, ok := _c.mutation.DueAt(); ok {
		_spec.SetField(loan.FieldDueAt, field.TypeTime, value)
		_node.DueAt = value
	}
	if value, ok := _c.mutation.ReturnedAt(); ok {
		_spec.SetField(loan.FieldReturnedAt, field.TypeTime, value)
		_node.ReturnedAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(loan.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.ReturnNotes(); ok {
		_spec.SetField(loan.FieldReturnNotes, field.TypeString, value)
		_node.ReturnNotes = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(loan.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.GroupTable,
			Columns: []string{loan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_loans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ItemTable,
			Columns: []string{loan.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_loans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.borrower_loans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CheckedOutByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.CheckedOutByTable,
			Columns: []string{loan.CheckedOutByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_checkouts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReturnedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ReturnedByTable,
			Columns: []string{loan.ReturnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_returns = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LoanCreateBulk is the builder for creating many Loan entities in bulk.
type LoanCreateBulk struct {
	config
	err      error
	builders []*LoanCreate
}

// Save creates the Loan entities in the database.
func (_c *LoanCreateBulk) Save(ctx context.Context) ([]*Loan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Loan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoanCreateBulk) SaveX(ctx context.Context) []*Loan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
