// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/loan"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// Loan is the model entity for the Loan schema.
type Loan struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// When the item was checked out
	CheckedOutAt time.Time `json:"checked_out_at,omitempty"`
	// When the item is expected to be returned
	DueAt time.Time `json:"due_at,omitempty"`
	// When the item was actually returned (null = still on loan)
	ReturnedAt *time.Time `json:"returned_at,omitempty"`
	// Notes made at checkout
	Notes string `json:"notes,omitempty"`
	// Notes made at return (e.g., condition)
	ReturnNotes string `json:"return_notes,omitempty"`
	// Number of items borrowed (for items with quantity > 1)
	Quantity int `json:"quantity,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoanQuery when eager-loading is set.
	Edges          LoanEdges `json:"edges"`
	borrower_loans *uuid.UUID
	group_loans    *uuid.UUID
	item_loans     *uuid.UUID
	user_checkouts *uuid.UUID
	user_returns   *uuid.UUID
	selectValues   sql.SelectValues
}

// LoanEdges holds the relations/edges for other nodes in the graph.
type LoanEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// Borrower holds the value of the borrower edge.
	Borrower *Borrower `json:"borrower,omitempty"`
	// CheckedOutBy holds the value of the checked_out_by edge.
	CheckedOutBy *User `json:"checked_out_by,omitempty"`
	// ReturnedBy holds the value of the returned_by edge.
	ReturnedBy *User `json:"returned_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoanEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoanEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// BorrowerOrErr returns the Borrower value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoanEdges) BorrowerOrErr() (*Borrower, error) {
	if e.Borrower != nil {
		return e.Borrower, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: borrower.Label}
	}
	return nil, &NotLoadedError{edge: "borrower"}
}

// CheckedOutByOrErr returns the CheckedOutBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoanEdges) CheckedOutByOrErr() (*User, error) {
	if e.CheckedOutBy != nil {
		return e.CheckedOutBy, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "checked_out_by"}
}

// ReturnedByOrErr returns the ReturnedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoanEdges) ReturnedByOrErr() (*User, error) {
	if e.ReturnedBy != nil {
		return e.ReturnedBy, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "returned_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Loan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loan.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case loan.FieldNotes, loan.FieldReturnNotes:
			values[i] = new(sql.NullString)
		case loan.FieldCreatedAt, loan.FieldUpdatedAt, loan.FieldCheckedOutAt, loan.FieldDueAt, loan.FieldReturnedAt:
			values[i] = new(sql.NullTime)
		case loan.FieldID:
			values[i] = new(uuid.UUID)
		case loan.ForeignKeys[0]: // borrower_loans
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case loan.ForeignKeys[1]: // group_loans
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case loan.ForeignKeys[2]: // item_loans
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case loan.ForeignKeys[3]: // user_checkouts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case loan.ForeignKeys[4]: // user_returns
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Loan fields.
func (_m *Loan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loan.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case loan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case loan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case loan.FieldCheckedOutAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_out_at", values[i])
			} else if value.Valid {
				_m.CheckedOutAt = value.Time
			}
		case loan.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_at", values[i])
			} else if value.Valid {
				_m.DueAt = value.Time
			}
		case loan.FieldReturnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field returned_at", values[i])
			} else if value.Valid {
				_m.ReturnedAt = new(time.Time)
				*_m.ReturnedAt = value.Time
			}
		case loan.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case loan.FieldReturnNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field return_notes", values[i])
			} else if value.Valid {
				_m.ReturnNotes = value.String
			}
		case loan.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case loan.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field borrower_loans", values[i])
			} else if value.Valid {
				_m.borrower_loans = new(uuid.UUID)
				*_m.borrower_loans = *value.S.(*uuid.UUID)
			}
		case loan.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_loans", values[i])
			} else if value.Valid {
				_m.group_loans = new(uuid.UUID)
				*_m.group_loans = *value.S.(*uuid.UUID)
			}
		case loan.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field item_loans", values[i])
			} else if value.Valid {
				_m.item_loans = new(uuid.UUID)
				*_m.item_loans = *value.S.(*uuid.UUID)
			}
		case loan.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_checkouts", values[i])
			} else if value.Valid {
				_m.user_checkouts = new(uuid.UUID)
				*_m.user_checkouts = *value.S.(*uuid.UUID)
			}
		case loan.ForeignKeys[4]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_returns", values[i])
			} else if value.Valid {
				_m.user_returns = new(uuid.UUID)
				*_m.user_returns = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Loan.
// This includes values selected through modifiers, order, etc.
func (_m *Loan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the Loan entity.
func (_m *Loan) QueryGroup() *GroupQuery {
	return NewLoanClient(_m.config).QueryGroup(_m)
}

// QueryItem queries the "item" edge of the Loan entity.
func (_m *Loan) QueryItem() *ItemQuery {
	return NewLoanClient(_m.config).QueryItem(_m)
}

// QueryBorrower queries the "borrower" edge of the Loan entity.
func (_m *Loan) QueryBorrower() *BorrowerQuery {
	return NewLoanClient(_m.config).QueryBorrower(_m)
}

// QueryCheckedOutBy queries the "checked_out_by" edge of the Loan entity.
func (_m *Loan) QueryCheckedOutBy() *UserQuery {
	return NewLoanClient(_m.config).QueryCheckedOutBy(_m)
}

// QueryReturnedBy queries the "returned_by" edge of the Loan entity.
func (_m *Loan) QueryReturnedBy() *UserQuery {
	return NewLoanClient(_m.config).QueryReturnedBy(_m)
}

// Update returns a builder for updating this Loan.
// Note that you need to call Loan.Unwrap() before calling this method if this Loan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Loan) Update() *LoanUpdateOne {
	return NewLoanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Loan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Loan) Unwrap() *Loan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Loan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Loan) String() string {
	var builder strings.Builder
	builder.WriteString("Loan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("checked_out_at=")
	builder.WriteString(_m.CheckedOutAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("due_at=")
	builder.WriteString(_m.DueAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReturnedAt; v != nil {
		builder.WriteString("returned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("return_notes=")
	builder.WriteString(_m.ReturnNotes)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteByte(')')
	return builder.String()
}

// Loans is a parsable slice of Loan.
type Loans []*Loan
