// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/borrower"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/item"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/loan"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// LoanUpdate is the builder for updating Loan entities.
type LoanUpdate struct {
	config
	hooks    []Hook
	mutation *LoanMutation
}

// Where appends a list predicates to the LoanUpdate builder.
func (_u *LoanUpdate) Where(ps ...predicate.Loan) *LoanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LoanUpdate) SetUpdatedAt(v time.Time) *LoanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (_u *LoanUpdate) SetCheckedOutAt(v time.Time) *LoanUpdate {
	_u.mutation.SetCheckedOutAt(v)
	return _u
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (_u *LoanUpdate) SetNillableCheckedOutAt(v *time.Time) *LoanUpdate {
	if v != nil {
		_u.SetCheckedOutAt(*v)
	}
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *LoanUpdate) SetDueAt(v time.Time) *LoanUpdate {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *LoanUpdate) SetNillableDueAt(v *time.Time) *LoanUpdate {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// SetReturnedAt sets the "returned_at" field.
func (_u *LoanUpdate) SetReturnedAt(v time.Time) *LoanUpdate {
	_u.mutation.SetReturnedAt(v)
	return _u
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (_u *LoanUpdate) SetNillableReturnedAt(v *time.Time) *LoanUpdate {
	if v != nil {
		_u.SetReturnedAt(*v)
	}
	return _u
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (_u *LoanUpdate) ClearReturnedAt() *LoanUpdate {
	_u.mutation.ClearReturnedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LoanUpdate) SetNotes(v string) *LoanUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LoanUpdate) SetNillableNotes(v *string) *LoanUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *LoanUpdate) ClearNotes() *LoanUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetReturnNotes sets the "return_notes" field.
func (_u *LoanUpdate) SetReturnNotes(v string) *LoanUpdate {
	_u.mutation.SetReturnNotes(v)
	return _u
}

// SetNillableReturnNotes sets the "return_notes" field if the given value is not nil.
func (_u *LoanUpdate) SetNillableReturnNotes(v *string) *LoanUpdate {
	if v != nil {
		_u.SetReturnNotes(*v)
	}
	return _u
}

// ClearReturnNotes clears the value of the "return_notes" field.
func (_u *LoanUpdate) ClearReturnNotes() *LoanUpdate {
	_u.mutation.ClearReturnNotes()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *LoanUpdate) SetQuantity(v int) *LoanUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *LoanUpdate) SetNillableQuantity(v *int) *LoanUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *LoanUpdate) AddQuantity(v int) *LoanUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *LoanUpdate) SetGroupID(id uuid.UUID) *LoanUpdate {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *LoanUpdate) SetGroup(v *Group) *LoanUpdate {
	return _u.SetGroupID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_u *LoanUpdate) SetItemID(id uuid.UUID) *LoanUpdate {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *LoanUpdate) SetItem(v *Item) *LoanUpdate {
	return _u.SetItemID(v.ID)
}

// SetBorrowerID sets the "borrower" edge to the Borrower entity by ID.
func (_u *LoanUpdate) SetBorrowerID(id uuid.UUID) *LoanUpdate {
	_u.mutation.SetBorrowerID(id)
	return _u
}

// SetBorrower sets the "borrower" edge to the Borrower entity.
func (_u *LoanUpdate) SetBorrower(v *Borrower) *LoanUpdate {
	return _u.SetBorrowerID(v.ID)
}

// SetCheckedOutByID sets the "checked_out_by" edge to the User entity by ID.
func (_u *LoanUpdate) SetCheckedOutByID(id uuid.UUID) *LoanUpdate {
	_u.mutation.SetCheckedOutByID(id)
	return _u
}

// SetNillableCheckedOutByID sets the "checked_out_by" edge to the User entity by ID if the given value is not nil.
func (_u *LoanUpdate) SetNillableCheckedOutByID(id *uuid.UUID) *LoanUpdate {
	if id != nil {
		_u = _u.SetCheckedOutByID(*id)
	}
	return _u
}

// SetCheckedOutBy sets the "checked_out_by" edge to the User entity.
func (_u *LoanUpdate) SetCheckedOutBy(v *User) *LoanUpdate {
	return _u.SetCheckedOutByID(v.ID)
}

// SetReturnedByID sets the "returned_by" edge to the User entity by ID.
func (_u *LoanUpdate) SetReturnedByID(id uuid.UUID) *LoanUpdate {
	_u.mutation.SetReturnedByID(id)
	return _u
}

// SetNillableReturnedByID sets the "returned_by" edge to the User entity by ID if the given value is not nil.
func (_u *LoanUpdate) SetNillableReturnedByID(id *uuid.UUID) *LoanUpdate {
	if id != nil {
		_u = _u.SetReturnedByID(*id)
	}
	return _u
}

// SetReturnedBy sets the "returned_by" edge to the User entity.
func (_u *LoanUpdate) SetReturnedBy(v *User) *LoanUpdate {
	return _u.SetReturnedByID(v.ID)
}

// Mutation returns the LoanMutation object of the builder.
func (_u *LoanUpdate) Mutation() *LoanMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *LoanUpdate) ClearGroup() *LoanUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *LoanUpdate) ClearItem() *LoanUpdate {
	_u.mutation.ClearItem()
	return _u
}

// ClearBorrower clears the "borrower" edge to the Borrower entity.
func (_u *LoanUpdate) ClearBorrower() *LoanUpdate {
	_u.mutation.ClearBorrower()
	return _u
}

// ClearCheckedOutBy clears the "checked_out_by" edge to the User entity.
func (_u *LoanUpdate) ClearCheckedOutBy() *LoanUpdate {
	_u.mutation.ClearCheckedOutBy()
	return _u
}

// ClearReturnedBy clears the "returned_by" edge to the User entity.
func (_u *LoanUpdate) ClearReturnedBy() *LoanUpdate {
	_u.mutation.ClearReturnedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LoanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := loan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoanUpdate) check() error {
	if v, ok := _u.mutation.Notes(); ok {
		if err := loan.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Loan.notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReturnNotes(); ok {
		if err := loan.ReturnNotesValidator(v); err != nil {
			return &ValidationError{Name: "return_notes", err: fmt.Errorf(`ent: validator failed for field "Loan.return_notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := loan.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Loan.quantity": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Loan.group"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Loan.item"`)
	}
	if _u.mutation.BorrowerCleared() && len(_u.mutation.BorrowerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Loan.borrower"`)
	}
	return nil
}

func (_u *LoanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loan.Table, loan.Columns, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(loan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckedOutAt(); ok {
		_spec.SetField(loan.FieldCheckedOutAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(loan.FieldDueAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReturnedAt(); ok {
		_spec.SetField(loan.FieldReturnedAt, field.TypeTime, value)
	}
	if _u.mutation.ReturnedAtCleared() {
		_spec.ClearField(loan.FieldReturnedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(loan.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(loan.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReturnNotes(); ok {
		_spec.SetField(loan.FieldReturnNotes, field.TypeString, value)
	}
	if _u.mutation.ReturnNotesCleared() {
		_spec.ClearField(loan.FieldReturnNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(loan.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(loan.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.GroupTable,
			Columns: []string{loan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.GroupTable,
			Columns: []string{loan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ItemTable,
			Columns: []string{loan.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ItemTable,
			Columns: []string{loan.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BorrowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CheckedOutByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.CheckedOutByTable,
			Columns: []string{loan.CheckedOutByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckedOutByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.CheckedOutByTable,
			Columns: []string{loan.CheckedOutByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReturnedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ReturnedByTable,
			Columns: []string{loan.ReturnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReturnedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ReturnedByTable,
			Columns: []string{loan.ReturnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoanUpdateOne is the builder for updating a single Loan entity.
type LoanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LoanUpdateOne) SetUpdatedAt(v time.Time) *LoanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (_u *LoanUpdateOne) SetCheckedOutAt(v time.Time) *LoanUpdateOne {
	_u.mutation.SetCheckedOutAt(v)
	return _u
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableCheckedOutAt(v *time.Time) *LoanUpdateOne {
	if v != nil {
		_u.SetCheckedOutAt(*v)
	}
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *LoanUpdateOne) SetDueAt(v time.Time) *LoanUpdateOne {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableDueAt(v *time.Time) *LoanUpdateOne {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// SetReturnedAt sets the "returned_at" field.
func (_u *LoanUpdateOne) SetReturnedAt(v time.Time) *LoanUpdateOne {
	_u.mutation.SetReturnedAt(v)
	return _u
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableReturnedAt(v *time.Time) *LoanUpdateOne {
	if v != nil {
		_u.SetReturnedAt(*v)
	}
	return _u
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (_u *LoanUpdateOne) ClearReturnedAt() *LoanUpdateOne {
	_u.mutation.ClearReturnedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LoanUpdateOne) SetNotes(v string) *LoanUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableNotes(v *string) *LoanUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *LoanUpdateOne) ClearNotes() *LoanUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetReturnNotes sets the "return_notes" field.
func (_u *LoanUpdateOne) SetReturnNotes(v string) *LoanUpdateOne {
	_u.mutation.SetReturnNotes(v)
	return _u
}

// SetNillableReturnNotes sets the "return_notes" field if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableReturnNotes(v *string) *LoanUpdateOne {
	if v != nil {
		_u.SetReturnNotes(*v)
	}
	return _u
}

// ClearReturnNotes clears the value of the "return_notes" field.
func (_u *LoanUpdateOne) ClearReturnNotes() *LoanUpdateOne {
	_u.mutation.ClearReturnNotes()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *LoanUpdateOne) SetQuantity(v int) *LoanUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableQuantity(v *int) *LoanUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *LoanUpdateOne) AddQuantity(v int) *LoanUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *LoanUpdateOne) SetGroupID(id uuid.UUID) *LoanUpdateOne {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *LoanUpdateOne) SetGroup(v *Group) *LoanUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_u *LoanUpdateOne) SetItemID(id uuid.UUID) *LoanUpdateOne {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *LoanUpdateOne) SetItem(v *Item) *LoanUpdateOne {
	return _u.SetItemID(v.ID)
}

// SetBorrowerID sets the "borrower" edge to the Borrower entity by ID.
func (_u *LoanUpdateOne) SetBorrowerID(id uuid.UUID) *LoanUpdateOne {
	_u.mutation.SetBorrowerID(id)
	return _u
}

// SetBorrower sets the "borrower" edge to the Borrower entity.
func (_u *LoanUpdateOne) SetBorrower(v *Borrower) *LoanUpdateOne {
	return _u.SetBorrowerID(v.ID)
}

// SetCheckedOutByID sets the "checked_out_by" edge to the User entity by ID.
func (_u *LoanUpdateOne) SetCheckedOutByID(id uuid.UUID) *LoanUpdateOne {
	_u.mutation.SetCheckedOutByID(id)
	return _u
}

// SetNillableCheckedOutByID sets the "checked_out_by" edge to the User entity by ID if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableCheckedOutByID(id *uuid.UUID) *LoanUpdateOne {
	if id != nil {
		_u = _u.SetCheckedOutByID(*id)
	}
	return _u
}

// SetCheckedOutBy sets the "checked_out_by" edge to the User entity.
func (_u *LoanUpdateOne) SetCheckedOutBy(v *User) *LoanUpdateOne {
	return _u.SetCheckedOutByID(v.ID)
}

// SetReturnedByID sets the "returned_by" edge to the User entity by ID.
func (_u *LoanUpdateOne) SetReturnedByID(id uuid.UUID) *LoanUpdateOne {
	_u.mutation.SetReturnedByID(id)
	return _u
}

// SetNillableReturnedByID sets the "returned_by" edge to the User entity by ID if the given value is not nil.
func (_u *LoanUpdateOne) SetNillableReturnedByID(id *uuid.UUID) *LoanUpdateOne {
	if id != nil {
		_u = _u.SetReturnedByID(*id)
	}
	return _u
}

// SetReturnedBy sets the "returned_by" edge to the User entity.
func (_u *LoanUpdateOne) SetReturnedBy(v *User) *LoanUpdateOne {
	return _u.SetReturnedByID(v.ID)
}

// Mutation returns the LoanMutation object of the builder.
func (_u *LoanUpdateOne) Mutation() *LoanMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *LoanUpdateOne) ClearGroup() *LoanUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *LoanUpdateOne) ClearItem() *LoanUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// ClearBorrower clears the "borrower" edge to the Borrower entity.
func (_u *LoanUpdateOne) ClearBorrower() *LoanUpdateOne {
	_u.mutation.ClearBorrower()
	return _u
}

// ClearCheckedOutBy clears the "checked_out_by" edge to the User entity.
func (_u *LoanUpdateOne) ClearCheckedOutBy() *LoanUpdateOne {
	_u.mutation.ClearCheckedOutBy()
	return _u
}

// ClearReturnedBy clears the "returned_by" edge to the User entity.
func (_u *LoanUpdateOne) ClearReturnedBy() *LoanUpdateOne {
	_u.mutation.ClearReturnedBy()
	return _u
}

// Where appends a list predicates to the LoanUpdate builder.
func (_u *LoanUpdateOne) Where(ps ...predicate.Loan) *LoanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoanUpdateOne) Select(field string, fields ...string) *LoanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Loan entity.
func (_u *LoanUpdateOne) Save(ctx context.Context) (*Loan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoanUpdateOne) SaveX(ctx context.Context) *Loan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LoanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := loan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoanUpdateOne) check() error {
	if v, ok := _u.mutation.Notes(); ok {
		if err := loan.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Loan.notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReturnNotes(); ok {
		if err := loan.ReturnNotesValidator(v); err != nil {
			return &ValidationError{Name: "return_notes", err: fmt.Errorf(`ent: validator failed for field "Loan.return_notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := loan.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Loan.quantity": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Loan.group"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Loan.item"`)
	}
	if _u.mutation.BorrowerCleared() && len(_u.mutation.BorrowerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Loan.borrower"`)
	}
	return nil
}

func (_u *LoanUpdateOne) sqlSave(ctx context.Context) (_node *Loan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loan.Table, loan.Columns, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Loan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loan.FieldID)
		for _, f := range fields {
			if !loan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(loan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckedOutAt(); ok {
		_spec.SetField(loan.FieldCheckedOutAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(loan.FieldDueAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReturnedAt(); ok {
		_spec.SetField(loan.FieldReturnedAt, field.TypeTime, value)
	}
	if _u.mutation.ReturnedAtCleared() {
		_spec.ClearField(loan.FieldReturnedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(loan.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(loan.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReturnNotes(); ok {
		_spec.SetField(loan.FieldReturnNotes, field.TypeString, value)
	}
	if _u.mutation.ReturnNotesCleared() {
		_spec.ClearField(loan.FieldReturnNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(loan.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(loan.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.GroupTable,
			Columns: []string{loan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.GroupTable,
			Columns: []string{loan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ItemTable,
			Columns: []string{loan.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ItemTable,
			Columns: []string{loan.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BorrowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(borrower.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CheckedOutByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.CheckedOutByTable,
			Columns: []string{loan.CheckedOutByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckedOutByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.CheckedOutByTable,
			Columns: []string{loan.CheckedOutByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReturnedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ReturnedByTable,
			Columns: []string{loan.ReturnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReturnedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.ReturnedByTable,
			Columns: []string{loan.ReturnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Loan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
