// Code generated by ent, DO NOT EDIT.

package loan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the loan type in the database.
	Label = "loan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCheckedOutAt holds the string denoting the checked_out_at field in the database.
	FieldCheckedOutAt = "checked_out_at"
	// FieldDueAt holds the string denoting the due_at field in the database.
	FieldDueAt = "due_at"
	// FieldReturnedAt holds the string denoting the returned_at field in the database.
	FieldReturnedAt = "returned_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldReturnNotes holds the string denoting the return_notes field in the database.
	FieldReturnNotes = "return_notes"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// EdgeBorrower holds the string denoting the borrower edge name in mutations.
	EdgeBorrower = "borrower"
	// EdgeCheckedOutBy holds the string denoting the checked_out_by edge name in mutations.
	EdgeCheckedOutBy = "checked_out_by"
	// EdgeReturnedBy holds the string denoting the returned_by edge name in mutations.
	EdgeReturnedBy = "returned_by"
	// Table holds the table name of the loan in the database.
	Table = "loans"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "loans"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_loans"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "loans"
	// ItemInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	ItemInverseTable = "items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "item_loans"
	// BorrowerTable is the table that holds the borrower relation/edge.
	BorrowerTable = "loans"
	// BorrowerInverseTable is the table name for the Borrower entity.
	// It exists in this package in order to avoid circular dependency with the "borrower" package.
	BorrowerInverseTable = "borrowers"
	// BorrowerColumn is the table column denoting the borrower relation/edge.
	BorrowerColumn = "borrower_loans"
	// CheckedOutByTable is the table that holds the checked_out_by relation/edge.
	CheckedOutByTable = "loans"
	// CheckedOutByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CheckedOutByInverseTable = "users"
	// CheckedOutByColumn is the table column denoting the checked_out_by relation/edge.
	CheckedOutByColumn = "user_checkouts"
	// ReturnedByTable is the table that holds the returned_by relation/edge.
	ReturnedByTable = "loans"
	// ReturnedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReturnedByInverseTable = "users"
	// ReturnedByColumn is the table column denoting the returned_by relation/edge.
	ReturnedByColumn = "user_returns"
)

// Columns holds all SQL columns for loan fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCheckedOutAt,
	FieldDueAt,
	FieldReturnedAt,
	FieldNotes,
	FieldReturnNotes,
	FieldQuantity,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "loans"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"borrower_loans",
	"group_loans",
	"item_loans",
	"user_checkouts",
	"user_returns",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCheckedOutAt holds the default value on creation for the "checked_out_at" field.
	DefaultCheckedOutAt func() time.Time
	// NotesValidator is a validator for the "notes" field. It is called by the builders before save.
	NotesValidator func(string) error
	// ReturnNotesValidator is a validator for the "return_notes" field. It is called by the builders before save.
	ReturnNotesValidator func(string) error
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Loan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCheckedOutAt orders the results by the checked_out_at field.
func ByCheckedOutAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedOutAt, opts...).ToFunc()
}

// ByDueAt orders the results by the due_at field.
func ByDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueAt, opts...).ToFunc()
}

// ByReturnedAt orders the results by the returned_at field.
func ByReturnedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByReturnNotes orders the results by the return_notes field.
func ByReturnNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnNotes, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByItemField orders the results by item field.
func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
	}
}

// ByBorrowerField orders the results by borrower field.
func ByBorrowerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBorrowerStep(), sql.OrderByField(field, opts...))
	}
}

// ByCheckedOutByField orders the results by checked_out_by field.
func ByCheckedOutByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckedOutByStep(), sql.OrderByField(field, opts...))
	}
}

// ByReturnedByField orders the results by returned_by field.
func ByReturnedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReturnedByStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
	)
}
func newBorrowerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BorrowerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BorrowerTable, BorrowerColumn),
	)
}
func newCheckedOutByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckedOutByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CheckedOutByTable, CheckedOutByColumn),
	)
}
func newReturnedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReturnedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReturnedByTable, ReturnedByColumn),
	)
}
