// Code generated by ent, DO NOT EDIT.

package loan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldUpdatedAt, v))
}

// CheckedOutAt applies equality check predicate on the "checked_out_at" field. It's identical to CheckedOutAtEQ.
func CheckedOutAt(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldCheckedOutAt, v))
}

// DueAt applies equality check predicate on the "due_at" field. It's identical to DueAtEQ.
func DueAt(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldDueAt, v))
}

// ReturnedAt applies equality check predicate on the "returned_at" field. It's identical to ReturnedAtEQ.
func ReturnedAt(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldReturnedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldNotes, v))
}

// ReturnNotes applies equality check predicate on the "return_notes" field. It's identical to ReturnNotesEQ.
func ReturnNotes(v string) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldReturnNotes, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldUpdatedAt, v))
}

// CheckedOutAtEQ applies the EQ predicate on the "checked_out_at" field.
func CheckedOutAtEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldCheckedOutAt, v))
}

// CheckedOutAtNEQ applies the NEQ predicate on the "checked_out_at" field.
func CheckedOutAtNEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldCheckedOutAt, v))
}

// CheckedOutAtIn applies the In predicate on the "checked_out_at" field.
func CheckedOutAtIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldCheckedOutAt, vs...))
}

// CheckedOutAtNotIn applies the NotIn predicate on the "checked_out_at" field.
func CheckedOutAtNotIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldCheckedOutAt, vs...))
}

// CheckedOutAtGT applies the GT predicate on the "checked_out_at" field.
func CheckedOutAtGT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldCheckedOutAt, v))
}

// CheckedOutAtGTE applies the GTE predicate on the "checked_out_at" field.
func CheckedOutAtGTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldCheckedOutAt, v))
}

// CheckedOutAtLT applies the LT predicate on the "checked_out_at" field.
func CheckedOutAtLT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldCheckedOutAt, v))
}

// CheckedOutAtLTE applies the LTE predicate on the "checked_out_at" field.
func CheckedOutAtLTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldCheckedOutAt, v))
}

// DueAtEQ applies the EQ predicate on the "due_at" field.
func DueAtEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldDueAt, v))
}

// DueAtNEQ applies the NEQ predicate on the "due_at" field.
func DueAtNEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldDueAt, v))
}

// DueAtIn applies the In predicate on the "due_at" field.
func DueAtIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldDueAt, vs...))
}

// DueAtNotIn applies the NotIn predicate on the "due_at" field.
func DueAtNotIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldDueAt, vs...))
}

// DueAtGT applies the GT predicate on the "due_at" field.
func DueAtGT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldDueAt, v))
}

// DueAtGTE applies the GTE predicate on the "due_at" field.
func DueAtGTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldDueAt, v))
}

// DueAtLT applies the LT predicate on the "due_at" field.
func DueAtLT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldDueAt, v))
}

// DueAtLTE applies the LTE predicate on the "due_at" field.
func DueAtLTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldDueAt, v))
}

// ReturnedAtEQ applies the EQ predicate on the "returned_at" field.
func ReturnedAtEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldReturnedAt, v))
}

// ReturnedAtNEQ applies the NEQ predicate on the "returned_at" field.
func ReturnedAtNEQ(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldReturnedAt, v))
}

// ReturnedAtIn applies the In predicate on the "returned_at" field.
func ReturnedAtIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldReturnedAt, vs...))
}

// ReturnedAtNotIn applies the NotIn predicate on the "returned_at" field.
func ReturnedAtNotIn(vs ...time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldReturnedAt, vs...))
}

// ReturnedAtGT applies the GT predicate on the "returned_at" field.
func ReturnedAtGT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldReturnedAt, v))
}

// ReturnedAtGTE applies the GTE predicate on the "returned_at" field.
func ReturnedAtGTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldReturnedAt, v))
}

// ReturnedAtLT applies the LT predicate on the "returned_at" field.
func ReturnedAtLT(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldReturnedAt, v))
}

// ReturnedAtLTE applies the LTE predicate on the "returned_at" field.
func ReturnedAtLTE(v time.Time) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldReturnedAt, v))
}

// ReturnedAtIsNil applies the IsNil predicate on the "returned_at" field.
func ReturnedAtIsNil() predicate.Loan {
	return predicate.Loan(sql.FieldIsNull(FieldReturnedAt))
}

// ReturnedAtNotNil applies the NotNil predicate on the "returned_at" field.
func ReturnedAtNotNil() predicate.Loan {
	return predicate.Loan(sql.FieldNotNull(FieldReturnedAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Loan {
	return predicate.Loan(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Loan {
	return predicate.Loan(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Loan {
	return predicate.Loan(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Loan {
	return predicate.Loan(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Loan {
	return predicate.Loan(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Loan {
	return predicate.Loan(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Loan {
	return predicate.Loan(sql.FieldContainsFold(FieldNotes, v))
}

// ReturnNotesEQ applies the EQ predicate on the "return_notes" field.
func ReturnNotesEQ(v string) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldReturnNotes, v))
}

// ReturnNotesNEQ applies the NEQ predicate on the "return_notes" field.
func ReturnNotesNEQ(v string) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldReturnNotes, v))
}

// ReturnNotesIn applies the In predicate on the "return_notes" field.
func ReturnNotesIn(vs ...string) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldReturnNotes, vs...))
}

// ReturnNotesNotIn applies the NotIn predicate on the "return_notes" field.
func ReturnNotesNotIn(vs ...string) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldReturnNotes, vs...))
}

// ReturnNotesGT applies the GT predicate on the "return_notes" field.
func ReturnNotesGT(v string) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldReturnNotes, v))
}

// ReturnNotesGTE applies the GTE predicate on the "return_notes" field.
func ReturnNotesGTE(v string) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldReturnNotes, v))
}

// ReturnNotesLT applies the LT predicate on the "return_notes" field.
func ReturnNotesLT(v string) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldReturnNotes, v))
}

// ReturnNotesLTE applies the LTE predicate on the "return_notes" field.
func ReturnNotesLTE(v string) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldReturnNotes, v))
}

// ReturnNotesContains applies the Contains predicate on the "return_notes" field.
func ReturnNotesContains(v string) predicate.Loan {
	return predicate.Loan(sql.FieldContains(FieldReturnNotes, v))
}

// ReturnNotesHasPrefix applies the HasPrefix predicate on the "return_notes" field.
func ReturnNotesHasPrefix(v string) predicate.Loan {
	return predicate.Loan(sql.FieldHasPrefix(FieldReturnNotes, v))
}

// ReturnNotesHasSuffix applies the HasSuffix predicate on the "return_notes" field.
func ReturnNotesHasSuffix(v string) predicate.Loan {
	return predicate.Loan(sql.FieldHasSuffix(FieldReturnNotes, v))
}

// ReturnNotesIsNil applies the IsNil predicate on the "return_notes" field.
func ReturnNotesIsNil() predicate.Loan {
	return predicate.Loan(sql.FieldIsNull(FieldReturnNotes))
}

// ReturnNotesNotNil applies the NotNil predicate on the "return_notes" field.
func ReturnNotesNotNil() predicate.Loan {
	return predicate.Loan(sql.FieldNotNull(FieldReturnNotes))
}

// ReturnNotesEqualFold applies the EqualFold predicate on the "return_notes" field.
func ReturnNotesEqualFold(v string) predicate.Loan {
	return predicate.Loan(sql.FieldEqualFold(FieldReturnNotes, v))
}

// ReturnNotesContainsFold applies the ContainsFold predicate on the "return_notes" field.
func ReturnNotesContainsFold(v string) predicate.Loan {
	return predicate.Loan(sql.FieldContainsFold(FieldReturnNotes, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.Loan {
	return predicate.Loan(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.Loan {
	return predicate.Loan(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.Loan {
	return predicate.Loan(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.Loan {
	return predicate.Loan(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.Loan {
	return predicate.Loan(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.Loan {
	return predicate.Loan(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.Loan {
	return predicate.Loan(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.Loan {
	return predicate.Loan(sql.FieldLTE(FieldQuantity, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBorrower applies the HasEdge predicate on the "borrower" edge.
func HasBorrower() predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BorrowerTable, BorrowerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBorrowerWith applies the HasEdge predicate on the "borrower" edge with a given conditions (other predicates).
func HasBorrowerWith(preds ...predicate.Borrower) predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := newBorrowerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCheckedOutBy applies the HasEdge predicate on the "checked_out_by" edge.
func HasCheckedOutBy() predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CheckedOutByTable, CheckedOutByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCheckedOutByWith applies the HasEdge predicate on the "checked_out_by" edge with a given conditions (other predicates).
func HasCheckedOutByWith(preds ...predicate.User) predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := newCheckedOutByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReturnedBy applies the HasEdge predicate on the "returned_by" edge.
func HasReturnedBy() predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReturnedByTable, ReturnedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReturnedByWith applies the HasEdge predicate on the "returned_by" edge with a given conditions (other predicates).
func HasReturnedByWith(preds ...predicate.User) predicate.Loan {
	return predicate.Loan(func(s *sql.Selector) {
		step := newReturnedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Loan) predicate.Loan {
	return predicate.Loan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Loan) predicate.Loan {
	return predicate.Loan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Loan) predicate.Loan {
	return predicate.Loan(sql.NotPredicates(p))
}
